### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
Apply last example_ynh

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
@Jojo144, yunohost package is ready

**Comment by Jojo144** [comment]
Thanks a lot for your contribution! I'll review it.
Unfortunately, I don't know when because I don't have time right now to do that. But I ut it on my TODO list!

**Comment by yalh76** [comment]
If you prefer, we can separate compteur_du_gase from the YunoHost package compteur_du_gase_ynh

**Pull request closed without merging**
